#!/usr/bin/env python
"""Phase2W context-headroom and micro-edit strategy analysis.

Research-only wrapper.  This script intentionally does not recompress point
clouds by default; it reuses existing CSVs generated by the SparsePCGC probes
and earlier Phase2 tools.  The goal is to avoid spending runs on all settings
while still answering:

* Which diagnostic 5/10% headroom rows are just coarse prune baselines?
* Which codec settings have measured occupancy-prediction headroom?
* Which existing Add/Prune/Adjust-style candidates actually improved raw bits?
* What small set of follow-up settings/candidates should be evaluated next?

It writes normalized CSV summaries and a Markdown report.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import statistics
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable, Mapping


csv.field_size_limit(sys.maxsize)

DEFAULT_RD_GRID = "reference/ToSSH/rd_probe_grid.csv"
DEFAULT_PSNR_SUMMARY = "reference/ToSSH/psnr5_multi_setting_summary.csv"
DEFAULT_OUTDIR = "/data/maejima/log/phase2w_context_headroom_micro_strategy"
DEFAULT_LOGS = (
    "/data/maejima/log/PHASE2V_psnr_grid_headroom.csv",
    "/data/maejima/log/PHASE2V_psnr_grid_selected_candidates.csv",
    "/data/maejima/log/PHASE2Q_probability_guided_context_edit.csv",
    "/data/maejima/log/PHASE2R_probability_flip_relocation_oracle.csv",
    "/data/maejima/log/PHASE2T_multi_rule_context_edit_headroom_smoke3.csv",
    "/data/maejima/log/PHASE2U_high_bit_candidate_rewrite_rd_smoke3_raw.csv",
)


def _rows(path: str) -> list[dict[str, str]]:
    if not path or not Path(path).exists():
        return []
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def _num(value: object, default: float = float("nan")) -> float:
    try:
        if value is None or value == "":
            return default
        return float(value)
    except Exception:
        return default


def _finite(value: object) -> bool:
    try:
        return math.isfinite(float(value))
    except Exception:
        return False


def _mean(values: Iterable[float]) -> float:
    vals = [float(v) for v in values if math.isfinite(float(v))]
    return float(sum(vals) / len(vals)) if vals else float("nan")


def _min(values: Iterable[float]) -> float:
    vals = [float(v) for v in values if math.isfinite(float(v))]
    return min(vals) if vals else float("nan")


def _max(values: Iterable[float]) -> float:
    vals = [float(v) for v in values if math.isfinite(float(v))]
    return max(vals) if vals else float("nan")


def _median(values: Iterable[float]) -> float:
    vals = [float(v) for v in values if math.isfinite(float(v))]
    return float(statistics.median(vals)) if vals else float("nan")


def _json_get(value: object, key: str) -> float:
    try:
        parsed = json.loads(str(value or "{}"))
        if isinstance(parsed, Mapping):
            return float(parsed.get(key, float("nan")))
    except Exception:
        pass
    return float("nan")


def _write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    keys: list[str] = []
    for row in rows:
        for key in row:
            if key not in keys:
                keys.append(key)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _operation_family(method: str) -> str:
    name = str(method or "").lower()
    if name in {"grid_stride", "random", "block_only", "high_bit_raw_prune"}:
        return "prune"
    if "snap" in name or "merge" in name:
        return "adjust_snap_merge"
    if "move" in name or "relocate" in name:
        return "adjust_move"
    if "add" in name or "repair" in name:
        return "add_or_repair"
    if name in {"codec_only", "headroom_noop", "noop", "no-op"}:
        return "none"
    return "mixed_or_unknown"


def diagnostic_headroom(psnr_rows: list[dict[str, str]], rd_rows: list[dict[str, str]]) -> list[dict[str, object]]:
    """Rows with 5/10% operations that improved while keeping D1/D2 within 0.5dB."""
    out: list[dict[str, object]] = []
    for r in psnr_rows:
        method = r.get("operation_method", "")
        if not method or method == "none":
            continue
        req = _num(r.get("operation_requested_percent"))
        before = _num(r.get("before_bit_size"))
        after = _num(r.get("after_bit_size"))
        d1 = _num(r.get("result_D1_PSNR")) - _num(r.get("baseline_D1_PSNR"))
        d2 = _num(r.get("result_D2_PSNR")) - _num(r.get("baseline_D2_PSNR"))
        if not all(math.isfinite(v) for v in (req, before, after, d1, d2)) or before <= 0:
            continue
        bd = 100.0 * (after - before) / before
        if req < 5.0 or bd >= 0 or abs(d1) > 0.5 or abs(d2) > 0.5:
            continue
        out.append({
            "source": "psnr5_multi_setting_summary",
            "setting_id": r.get("setting_id", ""),
            "method": method,
            "operation_family": _operation_family(method),
            "requested_ratio_percent": req,
            "actual_ratio_percent": _num(r.get("operation_actual_percent")),
            "BD_rate_equiv_percent": bd,
            "rate_improvement_percent": -bd,
            "rate_improvement_per_1pct_operation": (-bd / req) if req > 0 else "",
            "D1_delta": d1,
            "D2_delta": d2,
            "GT_bit": before,
            "MINE_bit": after,
            "PSNR_section": r.get("PSNR_section", ""),
            "note": "diagnostic_headroom_only_not_learning_target",
        })

    # rd_grid has more ratios, but usually no high-bit/snap actual bit columns.
    for r in rd_rows:
        method = r.get("voxel_op_method", "")
        if not method:
            continue
        req = _num(r.get("voxel_op_ratio_requested")) * 100.0
        before = _num(r.get("bit_size"))
        after = _num(r.get("voxel_op_bit_size"))
        d1 = _num(r.get("voxel_op_D1_PSNR")) - _num(r.get("D1_PSNR"))
        d2 = _num(r.get("voxel_op_D2_PSNR")) - _num(r.get("D2_PSNR"))
        if not all(math.isfinite(v) for v in (req, before, after, d1, d2)) or before <= 0:
            continue
        bd = 100.0 * (after - before) / before
        if req < 5.0 or bd >= 0 or abs(d1) > 0.5 or abs(d2) > 0.5:
            continue
        out.append({
            "source": "rd_probe_grid",
            "setting_id": r.get("setting_id", ""),
            "method": method,
            "operation_family": _operation_family(method),
            "requested_ratio_percent": req,
            "actual_ratio_percent": _num(r.get("voxel_op_actual_ratio")) * 100.0,
            "BD_rate_equiv_percent": bd,
            "rate_improvement_percent": -bd,
            "rate_improvement_per_1pct_operation": (-bd / req) if req > 0 else "",
            "D1_delta": d1,
            "D2_delta": d2,
            "GT_bit": before,
            "MINE_bit": after,
            "PSNR_section": r.get("target_psnr", ""),
            "note": "diagnostic_headroom_only_not_learning_target",
        })
    out.sort(key=lambda x: _num(x.get("BD_rate_equiv_percent")))
    return out


def micro_grid_summary(rd_rows: list[dict[str, str]], psnr_rows: list[dict[str, str]]) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []

    def add_row(source: str, setting: str, method: str, req_pct: float, act_pct: float, before: float, after: float, d1_delta: float, d2_delta: float, extra: Mapping[str, object]) -> None:
        if not all(math.isfinite(v) for v in (req_pct, before, after, d1_delta, d2_delta)) or before <= 0:
            return
        bd = 100.0 * (after - before) / before
        if req_pct > 3.0 or bd >= 0 or abs(d1_delta) > 0.5 or abs(d2_delta) > 0.5:
            return
        group = "primary_micro_leq1pct" if req_pct <= 1.0 else "extended_2to3pct"
        row = {
            "source": source,
            "setting_id": setting,
            "method": method,
            "operation_family": _operation_family(method),
            "ratio_priority_group": group,
            "requested_ratio_percent": req_pct,
            "actual_ratio_percent": act_pct,
            "BD_rate_equiv_percent": bd,
            "rate_improvement_percent": -bd,
            "rate_improvement_per_1pct_operation": (-bd / act_pct) if act_pct > 0 else "",
            "D1_delta": d1_delta,
            "D2_delta": d2_delta,
            "GT_bit": before,
            "MINE_bit": after,
        }
        row.update(extra)
        out.append(row)

    for r in rd_rows:
        method = r.get("voxel_op_method", "")
        if not method:
            continue
        add_row(
            "rd_probe_grid",
            r.get("setting_id", ""),
            method,
            _num(r.get("voxel_op_ratio_requested")) * 100.0,
            _num(r.get("voxel_op_actual_ratio")) * 100.0,
            _num(r.get("bit_size")),
            _num(r.get("voxel_op_bit_size")),
            _num(r.get("voxel_op_D1_PSNR")) - _num(r.get("D1_PSNR")),
            _num(r.get("voxel_op_D2_PSNR")) - _num(r.get("D2_PSNR")),
            {"target_psnr": r.get("target_psnr", "")},
        )
    for r in psnr_rows:
        method = r.get("operation_method", "")
        if not method or method == "none":
            continue
        add_row(
            "psnr5_multi_setting_summary",
            r.get("setting_id", ""),
            method,
            _num(r.get("operation_requested_percent")),
            _num(r.get("operation_actual_percent")),
            _num(r.get("before_bit_size")),
            _num(r.get("after_bit_size")),
            _num(r.get("result_D1_PSNR")) - _num(r.get("baseline_D1_PSNR")),
            _num(r.get("result_D2_PSNR")) - _num(r.get("baseline_D2_PSNR")),
            {"target_psnr": r.get("PSNR_section", "")},
        )
    out.sort(key=lambda x: (0 if x["ratio_priority_group"] == "primary_micro_leq1pct" else 1, _num(x["requested_ratio_percent"]), _num(x["BD_rate_equiv_percent"])))
    return out


def occupancy_setting_summary(log_rows: list[dict[str, str]]) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    seen: set[tuple[str, str, str]] = set()
    for r in log_rows:
        setting = r.get("setting_id") or r.get("codec_setting_id")
        if not setting:
            continue
        acc = _num(r.get("no_op_occupancy_acc_at_0p5") or r.get("occupancy_acc_at_0p5"))
        top3 = _num(r.get("top3p_high_bit_symbol_bit_share"))
        if not math.isfinite(acc) and not math.isfinite(top3):
            continue
        key = (str(setting), str(r.get("sequence", "")), str(r.get("frame_id", "")))
        if key in seen:
            continue
        seen.add(key)
        d1 = _num(r.get("no_op_decoded_D1_PSNR") or r.get("D1_PSNR"))
        out.append({
            "setting_id": setting,
            "codec_setting_id": r.get("codec_setting_id", ""),
            "dataset": r.get("dataset", ""),
            "sequence": r.get("sequence", ""),
            "frame_id": r.get("frame_id", ""),
            "voxel_size": r.get("voxel_size", ""),
            "pos_quantscale": r.get("pos_quantscale", ""),
            "no_op_occupancy_acc_at_0p5": acc,
            "occupied_recall": _num(r.get("occupied_recall")),
            "empty_accuracy": _num(r.get("empty_accuracy")),
            "p_true_q01": _num(r.get("p_true_q01"), _json_get(r.get("p_true_quantiles_json"), "q01")),
            "p_true_q05": _num(r.get("p_true_q05"), _json_get(r.get("p_true_quantiles_json"), "q05")),
            "p_true_median": _num(r.get("p_true_median"), _json_get(r.get("p_true_quantiles_json"), "q50")),
            "bit_each_q95": _num(r.get("bit_each_q95"), _json_get(r.get("bit_each_quantiles_json"), "q95")),
            "bit_each_q99": _num(r.get("bit_each_q99"), _json_get(r.get("bit_each_quantiles_json"), "q99")),
            "top1p_high_bit_symbol_bit_share": _num(r.get("top1p_high_bit_symbol_bit_share")),
            "top3p_high_bit_symbol_bit_share": top3,
            "top5p_high_bit_symbol_bit_share": _num(r.get("top5p_high_bit_symbol_bit_share")),
            "low_p_occupied_count": _num(r.get("low_p_occupied_count")),
            "high_p_empty_count": _num(r.get("high_p_empty_count")),
            "no_op_actual_bit_size": _num(r.get("no_op_actual_bit_size") or r.get("raw_bit") or r.get("base_bit")),
            "no_op_decoded_D1_PSNR": d1,
            "lossless": r.get("lossless", ""),
            "headroom_label": (
                "usable_rd_point" if math.isfinite(d1) and d1 >= 30.0
                else "broken_or_low_quality_setting"
            ),
        })
    out.sort(key=lambda r: (
        0 if r.get("headroom_label") == "usable_rd_point" else 1,
        -_num(r.get("top3p_high_bit_symbol_bit_share"), -1.0),
        _num(r.get("no_op_occupancy_acc_at_0p5"), 1.0),
    ))
    return out


def existing_candidate_summary(log_rows: list[dict[str, str]]) -> list[dict[str, object]]:
    groups: dict[tuple[str, float], list[dict[str, str]]] = defaultdict(list)
    for r in log_rows:
        raw = _num(r.get("actual_raw_percent"))
        if not math.isfinite(raw) or abs(raw) < 1e-12:
            continue
        name = r.get("candidate_name") or r.get("operation_type") or r.get("canonical_method") or "unknown"
        budget = _num(r.get("budget_ratio") or r.get("requested_budget_ratio") or r.get("edit_budget_ratio") or r.get("actual_edit_ratio"), 0.0)
        if budget > 1.0:
            budget = budget / 100.0
        groups[(name, budget)].append(r)

    out: list[dict[str, object]] = []
    for (name, budget), rows in groups.items():
        raws = [_num(r.get("actual_raw_percent")) for r in rows]
        d1 = [_num(r.get("D1_PSNR") or r.get("processed_decoded_d1_psnr")) for r in rows]
        chamfer = [_num(r.get("Chamfer") or r.get("processed_decoded_chamfer")) for r in rows]
        new_parent = [_num(r.get("new_parent_count"), 0.0) for r in rows]
        add_count = [_num(r.get("add_count"), 0.0) for r in rows]
        fam = Counter((_operation_family(name), *(r.get("candidate_family", "") for r in rows if r.get("candidate_family")))).most_common(1)
        out.append({
            "candidate_name": name,
            "operation_family": _operation_family(name),
            "budget_ratio": budget,
            "budget_percent": budget * 100.0,
            "row_count": len(rows),
            "mean_actual_raw_percent": _mean(raws),
            "best_actual_raw_percent": _min(raws),
            "worst_actual_raw_percent": _max(raws),
            "mean_raw_gain_per_1pct_edit": (-_mean(raws) / (budget * 100.0)) if budget > 0 and math.isfinite(_mean(raws)) else "",
            "mean_D1_PSNR": _mean(d1),
            "median_D1_PSNR": _median(d1),
            "mean_Chamfer": _mean(chamfer),
            "mean_new_parent_count": _mean(new_parent),
            "mean_add_count": _mean(add_count),
            "distinct_sequences": len(set(r.get("sequence", "") for r in rows)),
            "source_files_sample": ",".join(sorted(set(r.get("_source_file", "") for r in rows if r.get("_source_file")))[:4]),
        })
    out.sort(key=lambda r: (_num(r.get("budget_ratio")), _num(r.get("mean_actual_raw_percent"))))
    return out


def collect_logs(paths: list[str]) -> list[dict[str, str]]:
    out: list[dict[str, str]] = []
    for path in paths:
        for row in _rows(path):
            row = dict(row)
            row["_source_file"] = os.path.basename(path)
            out.append(row)
    return out


def _fmt(value: object, nd: int = 4) -> str:
    try:
        v = float(value)
        if not math.isfinite(v):
            return ""
        return f"{v:.{nd}f}"
    except Exception:
        return str(value or "")


def write_report(
    path: Path,
    *,
    diagnostic: list[dict[str, object]],
    micro: list[dict[str, object]],
    occupancy: list[dict[str, object]],
    candidates: list[dict[str, object]],
) -> None:
    top_diag = diagnostic[:8]
    top_micro = micro[:10]
    usable_occ = [r for r in occupancy if r.get("headroom_label") == "usable_rd_point"][:10]
    cand_best = sorted(candidates, key=lambda r: _num(r.get("mean_actual_raw_percent")))[:14]
    fam_counts = Counter(r.get("operation_family", "") for r in diagnostic)

    def md_table(rows: list[dict[str, object]], columns: list[str]) -> str:
        if not rows:
            return "_no rows_\n"
        s = "| " + " | ".join(columns) + " |\n"
        s += "| " + " | ".join(["---"] * len(columns)) + " |\n"
        for row in rows:
            s += "| " + " | ".join(_fmt(row.get(c)) for c in columns) + " |\n"
        return s

    report = f"""# Phase2W Context Headroom Micro Strategy

## 0. Short Conclusion

The existing <=1% rows in the attached grid are too weak by themselves.  They
do **not** yet support a 5-10% rate reduction from generic micro edits.

However, prior actual-bit-map / probability-guided probes already show a much
stronger path: at SparsePCGC default, high-bit prune / snap-to-existing reaches
about -1.3 to -1.5% at 1% edit and about -2.4 to -2.7% at 3% edit on 3-frame
smoke logs.  This means the next work should not be random/grid deletion.  It
should use diagnostic 5/10% prune rows as *where-to-look* headroom, then select
only high-leverage contexts using occupancy probability and bit_each.

The 5/10% diagnostic rows are operation families:

```json
{json.dumps(dict(fam_counts), ensure_ascii=False)}
```

So they are overwhelmingly prune baselines (`grid_stride` / `random`), not
evidence that Add or Adjust has already succeeded.

## 1. Diagnostic Headroom Rows

These are **not learning targets**; they identify settings where coarse deletion
can reveal bit headroom.

{md_table(top_diag, ["setting_id", "method", "operation_family", "requested_ratio_percent", "BD_rate_equiv_percent", "D1_delta", "D2_delta", "rate_improvement_per_1pct_operation"])}

## 2. Small-Ratio Rows From Attached CSVs

These are the direct attached-table candidates. They are much weaker than the
actual-bit guided probes.

{md_table(top_micro, ["setting_id", "method", "requested_ratio_percent", "BD_rate_equiv_percent", "D1_delta", "D2_delta", "rate_improvement_per_1pct_operation"])}

## 3. Occupancy Prediction / Context Headroom

For the attached dense AE/SR grid, occupancy columns were mostly unavailable in
`rd_probe_grid.csv`.  The following comes from existing Phase2V SparsePCGC
debug logs and is therefore only directly tied to voxel_size/pos_quantscale
settings, not every dense AE/SR tuple.

{md_table(usable_occ, ["setting_id", "voxel_size", "pos_quantscale", "no_op_occupancy_acc_at_0p5", "occupied_recall", "empty_accuracy", "top3p_high_bit_symbol_bit_share", "p_true_q05", "bit_each_q99", "no_op_decoded_D1_PSNR"])}

## 4. Existing Actual Candidate Evidence

This is the real clue: high-bit / low-prob / snap candidates beat random/grid
micro rows by a large margin, without Add-heavy behavior.

{md_table(cand_best, ["candidate_name", "operation_family", "budget_percent", "row_count", "mean_actual_raw_percent", "best_actual_raw_percent", "worst_actual_raw_percent", "mean_raw_gain_per_1pct_edit", "mean_new_parent_count", "mean_add_count"])}

## 5. Strategy For 5-10% With Few Edits

To plausibly reach 5-10% with 1-3% edits, the method must improve leverage by
roughly 2-4x beyond current high-bit prune/snap:

* current evidence: ~-1.3 to -1.5% at 1% edit, ~-2.5 to -2.7% at 3% edit.
* needed for -5% at 1% edit: ~5% / 1% edit, i.e. much higher than current.
* needed for -5% at 3% edit: ~1.67% / 1% edit, closer but still above current.

Therefore the next probe should target *context transformations*, not more
greedy sparse deletion:

1. Start from the diagnostic headroom settings (`dense_bd13_vs1_pq1_ae1_sr1`,
   `dense_bd14_vs1_pq1_ae1_sr2`) only as high-headroom contexts.
2. Run occupancy debug for those exact dense settings if possible; current
   attached CSV does not contain occupancy probabilities for them.
3. Extract parent/child contexts where coarse grid_stride deletion removed many
   bits.
4. Replace coarse deletion with:
   * low-prob occupied -> snap/merge to existing occupied,
   * parent pattern popcount reduction by 1 only,
   * no-new-parent Adjust,
   * entropy-reducing Add only if actual/debug estimated_bits_delta is negative.
5. Actual encode only top candidates; reject any candidate with new_parent_count
   or isolated_add_count unless it demonstrably lowers actual raw bits.

## 6. What Not To Do

Blindly pruning sparse regions is exactly the wrong abstraction.  The diagnostic
grid_stride rows show that deletion can expose headroom, but not that sparse
region deletion is a good policy.  The policy should be bit/context-first:

* source must have high bit_each or low p_true.
* edit must reduce parent/context entropy or actual estimated bits.
* Add must be paired with net entropy reduction; empty-target Add alone is not
  trusted.
* Adjust should prefer existing occupied targets or same-parent moves that do
  not create a new parent.

## 7. Recommended Minimal Next Run

Do not run all seven settings.  Run only:

1. `dense_bd15_vs1_pq1_ae1_sr6`: best small-ratio attached-table setting.
2. `dense_bd13_vs1_pq1_ae1_sr1`: diagnostic -14.9% headroom setting.
3. `dense_bd14_vs1_pq1_ae1_sr2`: diagnostic -14.9% headroom setting.

For each setting, test only 0.25%, 0.5%, 1%, 2%, 3% budgets with:

* high_bit_raw_prune,
* low_prob_snap_to_existing,
* snap_to_existing_only,
* parent_popcount_reduce_1,
* no_new_parent_adjust,
* entropy_reducing_add_repair.

The success criterion should be raw_gain_per_1pct_edit, not absolute gain from
large deletion.
"""
    path.write_text(report, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rd-grid", default=DEFAULT_RD_GRID)
    parser.add_argument("--psnr-summary", default=DEFAULT_PSNR_SUMMARY)
    parser.add_argument("--logs", default=",".join(DEFAULT_LOGS))
    parser.add_argument("--outdir", default=DEFAULT_OUTDIR)
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    rd_rows = _rows(args.rd_grid)
    psnr_rows = _rows(args.psnr_summary)
    log_paths = [x.strip() for x in str(args.logs).split(",") if x.strip()]
    log_rows = collect_logs(log_paths)

    diagnostic = diagnostic_headroom(psnr_rows, rd_rows)
    micro = micro_grid_summary(rd_rows, psnr_rows)
    occupancy = occupancy_setting_summary(log_rows)
    candidates = existing_candidate_summary(log_rows)

    _write_csv(outdir / "diagnostic_headroom_operations.csv", diagnostic)
    _write_csv(outdir / "small_ratio_attached_csv_candidates.csv", micro)
    _write_csv(outdir / "occupancy_prediction_by_setting.csv", occupancy)
    _write_csv(outdir / "existing_actual_candidate_summary.csv", candidates)
    write_report(outdir / "phase2w_context_headroom_micro_strategy.md", diagnostic=diagnostic, micro=micro, occupancy=occupancy, candidates=candidates)

    print(f"Wrote {outdir}")
    print(f"diagnostic_headroom_rows={len(diagnostic)}")
    print(f"small_ratio_rows={len(micro)}")
    print(f"occupancy_rows={len(occupancy)}")
    print(f"candidate_groups={len(candidates)}")


if __name__ == "__main__":
    main()
