import math

from .actual_codec_status import is_fresh_actual
from .scalar_utils import case_float, case_int, summarize_octree_level_debug
from .sparsepcgc_controls import add_warmup_factor, sparsepcgc_add_experiment_active

def build_compression_metric_row(
    args,
    *,
    global_step,
    episode,
    epoch,
    step,
    stage,
    comp_debug,
    L_com,
):
    actual_delta = case_float(comp_debug.get("actual_total_bit_percent", float("nan")), float("nan"))
    fresh_actual = is_fresh_actual(args, comp_debug)
    cached_actual = math.isfinite(actual_delta) and not fresh_actual
    return {
        "global_step": int(global_step) + 1,
        "episode": int(episode) + 1,
        "epoch": int(epoch) + 1,
        "step": int(step) + 1,
        "stage": str(stage),
        "codec": str(comp_debug.get("teacher_codec", getattr(args, "compress", "unknown"))),
        "backend": str(getattr(args, "compression_loss_backend", "proxy")),
        "actual_value_source": str(comp_debug.get("actual_value_source", "unknown")),
        "fresh_actual": bool(fresh_actual),
        "cached_actual": bool(cached_actual),
        "actual_total_bit_percent": actual_delta if math.isfinite(actual_delta) else None,
        "actual_total_bit_percent_fresh": actual_delta if fresh_actual else None,
        "actual_total_bit_percent_cached": actual_delta if cached_actual else None,
        "compression_loss_L_com": case_float(L_com, float("nan")),
        "lcom_main": case_float(comp_debug.get("compression_main_loss", float("nan")), float("nan")),
        "lcom_aux": case_float(comp_debug.get("compression_aux_loss", float("nan")), float("nan")),
        "lcom_sparsepcgc_aux": case_float(comp_debug.get("sparsepcgc_aux_loss", float("nan")), float("nan")),
        "sparsepcgc_aux_raw": case_float(comp_debug.get("sparsepcgc_aux_raw", comp_debug.get("sparsepcgc_aux_loss", float("nan"))), float("nan")),
        "sparsepcgc_aux_weighted": case_float(comp_debug.get("sparsepcgc_aux_weighted", float("nan")), float("nan")),
        "sparsepcgc_aux_backprop": bool(comp_debug.get("sparsepcgc_aux_backprop", False)),
        "lcom_without_sparsepcgc_aux": case_float(comp_debug.get("lcom_without_sparsepcgc_aux", float("nan")), float("nan")),
        "lcom_with_sparsepcgc_aux": case_float(comp_debug.get("lcom_with_sparsepcgc_aux", comp_debug.get("compression_objective", float("nan"))), float("nan")),
        "lcom_objective": case_float(comp_debug.get("compression_objective", comp_debug.get("total_bit", float("nan"))), float("nan")),
        "compression_main_grad_scale": case_float(comp_debug.get("compression_main_grad_scale", 1.0), 1.0),
        "compression_aux_in_objective": bool(comp_debug.get("compression_aux_in_objective", False)),
        "surrogate_auto_frozen": bool(comp_debug.get("surrogate_auto_frozen", False)),
        "surrogate_auto_freeze_streak": case_int(comp_debug.get("surrogate_auto_freeze_streak", 0), 0),
        "com_sparsepcgc_weight": case_float(getattr(args, "com_sparsepcgc", float("nan")), float("nan")),
        "sparsepcgc_aux_weight": case_float(getattr(args, "com_sparsepcgc", float("nan")), float("nan")),
        "sparsepcgc_active_coord_loss": case_float(comp_debug.get("sparsepcgc_active_coord_loss", float("nan")), float("nan")),
        "sparsepcgc_isolated_loss": case_float(comp_debug.get("sparsepcgc_isolated_proxy_loss", float("nan")), float("nan")),
        "sparsepcgc_entropy_loss": case_float(comp_debug.get("sparsepcgc_entropy_proxy_loss", float("nan")), float("nan")),
        "sparsepcgc_density_loss": case_float(comp_debug.get("sparsepcgc_density_proxy_loss", float("nan")), float("nan")),
        "sparsepcgc_single_aux": case_float(comp_debug.get("soft_single_percent", float("nan")), float("nan")),
        "sparsepcgc_node_aux": case_float(comp_debug.get("soft_node_percent", float("nan")), float("nan")),
        "compression_objective": case_float(comp_debug.get("compression_objective", comp_debug.get("total_bit", float("nan"))), float("nan")),
        "compression_main_loss": case_float(comp_debug.get("compression_main_loss", float("nan")), float("nan")),
        "compression_aux_loss": case_float(comp_debug.get("compression_aux_loss", float("nan")), float("nan")),
        "sparsepcgc_aux_loss": case_float(comp_debug.get("sparsepcgc_aux_loss", float("nan")), float("nan")),
        "surrogate_pred_bit_percent": case_float(comp_debug.get("surrogate_pred_bit", float("nan")), float("nan")),
        "surrogate_target_bit_percent": case_float(comp_debug.get("surrogate_target_bit", float("nan")), float("nan")),
        "surrogate_abs_bit_error": case_float(comp_debug.get("surrogate_abs_bit_error", float("nan")), float("nan")),
        "surrogate_signed_bit_error": case_float(comp_debug.get("surrogate_signed_bit_error", float("nan")), float("nan")),
        "surrogate_train_loss": case_float(comp_debug.get("surrogate_train_loss", float("nan")), float("nan")),
        "proxy_delta_percent": case_float(comp_debug.get("rate_proxy_delta", comp_debug.get("total_bit", float("nan"))), float("nan")),
        "actual_bits_before": case_float(comp_debug.get("gt_actual_bit", comp_debug.get("gt_bit_abs", float("nan"))), float("nan")),
        "actual_bits_after": case_float(comp_debug.get("gen_actual_bit", comp_debug.get("gen_bit_abs", float("nan"))), float("nan")),
        "point_count_before": case_int(comp_debug.get("gt_points", 0)),
        "point_count_after": case_int(comp_debug.get("gen_points", 0)),
        "unique_coord_before": case_int(comp_debug.get("gt_unique_coord_count", 0)),
        "unique_coord_after": case_int(comp_debug.get("gen_unique_coord_count", 0)),
        "node_delta": case_float(comp_debug.get("node_delta", float("nan")), float("nan")),
        "single_delta": case_float(comp_debug.get("single_delta", float("nan")), float("nan")),
        "teacher_refresh": bool(comp_debug.get("teacher_refresh", False)),
        "teacher_cache_hit": comp_debug.get("teacher_cache_hit", None),
        "teacher_target_age": case_int(comp_debug.get("teacher_target_age", 0)),
        "actual_codec_disabled": bool(comp_debug.get("actual_codec_disabled_during_train", False)),
        "actual_codec_skipped_by_interval": bool(comp_debug.get("actual_codec_skipped_by_interval", False)),
        "actual_codec_fallback_to_proxy": bool(comp_debug.get("actual_codec_fallback_to_proxy", False)),
        "loss_mode": str(comp_debug.get("loss_mode", getattr(args, "loss_mode", "legacy_total"))),
        "cp_main_source": str(comp_debug.get("cp_main_source", "")),
        "cp_warmup": case_float(comp_debug.get("cp_warmup", float("nan")), float("nan")),
        "cp_L_com_main": case_float(comp_debug.get("cp_L_com_main", float("nan")), float("nan")),
        "cp_L_com_primary": case_float(comp_debug.get("cp_L_com_primary", float("nan")), float("nan")),
        "cp_P_geom": case_float(comp_debug.get("cp_P_geom", float("nan")), float("nan")),
        "cp_P_single": case_float(comp_debug.get("cp_P_single", float("nan")), float("nan")),
        "cp_P_nodes": case_float(comp_debug.get("cp_P_nodes", float("nan")), float("nan")),
        "cp_P_sparsepcgc": case_float(comp_debug.get("cp_P_sparsepcgc", float("nan")), float("nan")),
        "cp_P_actuator": case_float(comp_debug.get("cp_P_actuator", float("nan")), float("nan")),
        "cp_P_op": case_float(comp_debug.get("cp_P_op", float("nan")), float("nan")),
        "cp_total": case_float(comp_debug.get("cp_total", float("nan")), float("nan")),
        "cp_main_requires_grad": comp_debug.get("cp_main_requires_grad", None),
        "cp_geom_requires_grad": comp_debug.get("cp_geom_requires_grad", None),
        "cp_single_requires_grad": comp_debug.get("cp_single_requires_grad", None),
        "cp_nodes_requires_grad": comp_debug.get("cp_nodes_requires_grad", None),
        "cp_sparsepcgc_requires_grad": comp_debug.get("cp_sparsepcgc_requires_grad", None),
        "cp_actuator_requires_grad": comp_debug.get("cp_actuator_requires_grad", None),
        "cp_op_requires_grad": comp_debug.get("cp_op_requires_grad", None),
        "cp_main_finite": comp_debug.get("cp_main_finite", None),
        "cp_geom_finite": comp_debug.get("cp_geom_finite", None),
        "cp_single_finite": comp_debug.get("cp_single_finite", None),
        "cp_nodes_finite": comp_debug.get("cp_nodes_finite", None),
        "cp_sparsepcgc_finite": comp_debug.get("cp_sparsepcgc_finite", None),
        "cp_actuator_finite": comp_debug.get("cp_actuator_finite", None),
        "cp_op_finite": comp_debug.get("cp_op_finite", None),
        "corr_surrogate_actual": case_float(comp_debug.get("corr_surrogate_actual", float("nan")), float("nan")),
        "corr_lcom_actual": case_float(comp_debug.get("corr_lcom_actual", float("nan")), float("nan")),
        "corr_cp_main_actual": case_float(comp_debug.get("corr_cp_main_actual", float("nan")), float("nan")),
        "corr_sparsepcgc_aux_actual": case_float(comp_debug.get("corr_sparsepcgc_aux_actual", float("nan")), float("nan")),
        "corr_lcom_without_sparsepcgc_aux_actual": case_float(comp_debug.get("corr_lcom_without_sparsepcgc_aux_actual", float("nan")), float("nan")),
        "sign_match_surrogate_actual": case_float(comp_debug.get("sign_match_surrogate_actual", float("nan")), float("nan")),
        "sign_match_lcom_actual": case_float(comp_debug.get("sign_match_lcom_actual", float("nan")), float("nan")),
        "sign_match_cp_main_actual": case_float(comp_debug.get("sign_match_cp_main_actual", float("nan")), float("nan")),
        "sign_match_sparsepcgc_aux_actual": case_float(comp_debug.get("sign_match_sparsepcgc_aux_actual", float("nan")), float("nan")),
        "sign_match_lcom_without_sparsepcgc_aux_actual": case_float(comp_debug.get("sign_match_lcom_without_sparsepcgc_aux_actual", float("nan")), float("nan")),
        "rolling_corr_window": case_int(comp_debug.get("rolling_corr_window", getattr(args, "sparsepcgc_corr_window", 100))),
        "rolling_sign_match_window": case_int(comp_debug.get("rolling_sign_match_window", getattr(args, "sparsepcgc_corr_window", 100))),
        "active_coord_before": case_int(comp_debug.get("sparsepcgc_before_active_coords", 0)),
        "active_coord_after": case_int(comp_debug.get("sparsepcgc_after_active_coords", 0)),
        "active_coord_delta": case_int(comp_debug.get("sparsepcgc_active_coord_delta", 0)),
        "isolated_voxel_count": case_int(comp_debug.get("sparsepcgc_after_isolated_voxels", 0)),
        "isolated_voxel_delta": case_int(comp_debug.get("sparsepcgc_isolated_delta", 0)),
        "sparse_density_before": case_float(comp_debug.get("sparsepcgc_before_sparse_density", float("nan")), float("nan")),
        "sparse_density_after": case_float(comp_debug.get("sparsepcgc_after_sparse_density", float("nan")), float("nan")),
        "sparse_density_delta": case_float(comp_debug.get("sparsepcgc_sparse_density_delta", float("nan")), float("nan")),
        "occupancy_entropy": case_float(comp_debug.get("occupancy_entropy", comp_debug.get("sparsepcgc_entropy_proxy_loss", float("nan"))), float("nan")),
        "occupancy_nll_proxy": case_float(comp_debug.get("occupancy_nll_proxy", float("nan")), float("nan")),
        "lowprob_occupancy_ratio": case_float(comp_debug.get("lowprob_occupancy_ratio", float("nan")), float("nan")),
        "entropy_delta": case_float(comp_debug.get("sparsepcgc_entropy_proxy_loss", float("nan")), float("nan")),
        "nll_delta": case_float(comp_debug.get("nll_delta", comp_debug.get("occupancy_nll_proxy", float("nan"))), float("nan")),
    }


def build_operation_metric_row(
    args,
    *,
    global_step,
    episode,
    epoch,
    step,
    stage,
    comp_debug,
    structure_debug,
    edit_stats,
):
    actual_delta = case_float(comp_debug.get("actual_total_bit_percent", float("nan")), float("nan"))
    unique_before = case_int(comp_debug.get("gt_unique_coord_count", 0))
    unique_after = case_int(comp_debug.get("gen_unique_coord_count", 0))
    edit_stats = edit_stats or {}
    input_points = case_float(edit_stats.get("input_points_avg", edit_stats.get("input_points", float("nan"))), float("nan"))
    add_candidate_ratio = case_float(structure_debug.get("add_candidate_ratio", float("nan")), float("nan"))
    add_candidate_count = None
    if math.isfinite(input_points) and math.isfinite(add_candidate_ratio):
        add_candidate_count = int(round(input_points * add_candidate_ratio))
        if add_candidate_ratio > 0.0 and input_points > 0.0:
            add_candidate_count = max(add_candidate_count, 1)
    add_effective_count = case_int(structure_debug.get("add_effective_count", structure_debug.get("add_actual_point_count", 0)))
    unique_delta = unique_after - unique_before
    positive_unique_delta = max(unique_delta, 0)
    add_removed_by_unique = max(add_effective_count - positive_unique_delta, 0)
    active_before = case_int(comp_debug.get("sparsepcgc_before_active_coords", 0))
    active_after = case_int(comp_debug.get("sparsepcgc_after_active_coords", 0))
    level_debug = structure_debug.get("octree_level_debug") or []
    return {
        "global_step": int(global_step) + 1,
        "episode": int(episode) + 1,
        "epoch": int(epoch) + 1,
        "step": int(step) + 1,
        "stage": str(stage),
        "codec": str(comp_debug.get("teacher_codec", getattr(args, "compress", "unknown"))),
        "fresh_actual": bool(is_fresh_actual(args, comp_debug)),
        "actual_total_bit_percent": actual_delta if math.isfinite(actual_delta) else None,
        "train_or_eval_mode": "train",
        "hardening_mode": str(edit_stats.get("keep_mode", "")),
        "selection_threshold": case_float(getattr(args, "operation_count_drop_threshold", 0.5), float("nan")),
        "topk_selected_count": case_int(edit_stats.get("output_points", 0)),
        "sparsepcgc_add_experiment_enabled": bool(sparsepcgc_add_experiment_active(args)),
        "add_enabled": bool(structure_debug.get("add_enabled", False)),
        "prune_enabled": bool(structure_debug.get("prune_enabled", False)),
        "disp_enabled": bool(structure_debug.get("disp_enabled", False)),
        "repair_ratio": case_float(structure_debug.get("repair_ratio", float("nan")), float("nan")),
        "preserve_ratio": case_float(structure_debug.get("preserve_ratio", float("nan")), float("nan")),
        "add_prob_mean": case_float(structure_debug.get("add_prob_mean", float("nan")), float("nan")),
        "add_prob_max": case_float(structure_debug.get("add_prob_max", float("nan")), float("nan")),
        "add_priority_mean": case_float(structure_debug.get("add_priority_mean", float("nan")), float("nan")),
        "add_priority_max": case_float(structure_debug.get("add_priority_max", float("nan")), float("nan")),
        "add_score_mean": case_float(structure_debug.get("add_priority_mean", float("nan")), float("nan")),
        "add_score_max": case_float(structure_debug.get("add_priority_max", float("nan")), float("nan")),
        "add_ratio": case_float(structure_debug.get("add_ratio", float("nan")), float("nan")),
        "add_candidate_ratio": add_candidate_ratio,
        "add_candidate_count": add_candidate_count,
        "add_hard_count": case_int(structure_debug.get("add_count", 0)),
        "add_effective_count": add_effective_count,
        "add_actual_point_count": add_effective_count,
        "add_target_voxels": case_int(structure_debug.get("add_target_voxel_count", 0)),
        "add_target_ratio": case_float(getattr(args, "target_add_ratio", 0.0), float("nan")),
        "add_max_ratio": case_float(getattr(args, "max_add_ratio", 0.0), float("nan")),
        "add_warmup": add_warmup_factor(args),
        "soft_add_count": case_float(structure_debug.get("add_ratio", 0.0), 0.0) * input_points if math.isfinite(input_points) else None,
        "hard_add_count": case_int(structure_debug.get("add_count", 0)),
        "drop_prob_mean": case_float(structure_debug.get("drop_ratio", float("nan")), float("nan")),
        "hard_drop_ratio": case_float(structure_debug.get("hard_drop_ratio", float("nan")), float("nan")),
        "hard_drop_count": case_int(structure_debug.get("hard_drop_count", structure_debug.get("delete_removed_point_count", 0))),
        "delete_target_voxels": case_int(structure_debug.get("delete_target_voxel_count", 0)),
        "delete_emptied_voxels": case_int(structure_debug.get("delete_emptied_voxel_count", 0)),
        "move_score_mean": case_float(structure_debug.get("move_score_mean", float("nan")), float("nan")),
        "hard_move_ratio": case_float(structure_debug.get("move_ratio", float("nan")), float("nan")),
        "hard_move_count": case_int(structure_debug.get("hard_move_count", 0)),
        "move_source_voxels": case_int(structure_debug.get("move_source_voxel_count", 0)),
        "move_target_voxels": case_int(structure_debug.get("move_target_voxel_count", 0)),
        "move_source_emptied": case_int(structure_debug.get("move_source_emptied_voxel_count", 0)),
        "move_target_new": case_int(structure_debug.get("move_target_new_voxel_count", 0)),
        "move_source_not_emptied": case_int(structure_debug.get("move_source_not_emptied_count", 0)),
        "same_voxel_adjust": case_int(structure_debug.get("same_voxel_adjust_count", 0)),
        "different_voxel_move": case_int(structure_debug.get("moved_different_voxel_count", 0)),
        "input_points": input_points,
        "pre_output_points": case_float(edit_stats.get("pre_output_points_avg", edit_stats.get("pre_output_points", float("nan"))), float("nan")),
        "output_points": case_float(edit_stats.get("output_points_avg", edit_stats.get("output_points", float("nan"))), float("nan")),
        "added_ratio_percent": case_float(edit_stats.get("added_ratio_percent", float("nan")), float("nan")),
        "deleted_ratio_percent": case_float(edit_stats.get("deleted_ratio_percent", float("nan")), float("nan")),
        "adjusted_ratio_percent": case_float(edit_stats.get("adjusted_ratio_percent", float("nan")), float("nan")),
        "codec_points_after": case_int(comp_debug.get("gen_points", 0)),
        "codec_points_before": case_int(comp_debug.get("gt_points", 0)),
        "codec_unique_after": unique_after,
        "codec_unique_before": unique_before,
        "unique_coord_delta": unique_delta,
        "add_after_quant_unique_count": positive_unique_delta,
        "add_removed_by_unique_count": add_removed_by_unique,
        "active_coord_before": active_before,
        "active_coord_after": active_after,
        "active_coord_delta": active_after - active_before,
        "isolated_voxel_count": case_int(comp_debug.get("sparsepcgc_after_isolated_voxels", 0)),
        "isolated_voxel_delta": case_int(comp_debug.get("sparsepcgc_isolated_delta", 0)),
        "sparse_density_before": case_float(comp_debug.get("sparsepcgc_before_sparse_density", float("nan")), float("nan")),
        "sparse_density_after": case_float(comp_debug.get("sparsepcgc_after_sparse_density", float("nan")), float("nan")),
        "sparse_density_delta": case_float(comp_debug.get("sparsepcgc_sparse_density_delta", float("nan")), float("nan")),
        "occupancy_entropy": case_float(structure_debug.get("occupancy_entropy", comp_debug.get("occupancy_entropy", float("nan"))), float("nan")),
        "occupancy_nll_proxy": case_float(structure_debug.get("occupancy_nll_proxy", comp_debug.get("occupancy_nll_proxy", float("nan"))), float("nan")),
        "lowprob_occupancy_ratio": case_float(structure_debug.get("lowprob_occupancy_ratio", comp_debug.get("lowprob_occupancy_ratio", float("nan"))), float("nan")),
        "entropy_delta": case_float(comp_debug.get("sparsepcgc_entropy_proxy_loss", float("nan")), float("nan")),
        "nll_delta": case_float(comp_debug.get("nll_delta", structure_debug.get("occupancy_nll_proxy", float("nan"))), float("nan")),
        "depth_node_count_summary": summarize_octree_level_debug(level_debug, "occupied_mean"),
        "depth_single_child_count_summary": summarize_octree_level_debug(level_debug, "single_mean"),
        "depth_entropy_summary": summarize_octree_level_debug(level_debug, "std_children_mean"),
        "depth_lowprob_summary": summarize_octree_level_debug(level_debug, "single_ratio_mean"),
        "subtree_depth": case_int(structure_debug.get("subtree_depth", getattr(args, "_current_subtree_depth", 0))),
        "subtree_node_count": case_float(structure_debug.get("subtree_node_count", float("nan")), float("nan")),
        "subtree_single_child_count": case_float(structure_debug.get("subtree_single_child_count", float("nan")), float("nan")),
        "single_child_delta": case_float(comp_debug.get("single_delta", float("nan")), float("nan")),
        "cp_L_com_main": case_float(comp_debug.get("cp_L_com_main", float("nan")), float("nan")),
        "cp_total": case_float(comp_debug.get("cp_total", float("nan")), float("nan")),
    }
